server:
  port: 8085
spring:
  application:
    name: hmdp-plus
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true  
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere.yaml
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    servlet:
      load-on-startup: 1    
  jackson:
    default-property-inclusion: non_null # Ignore null fields during JSON processing
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    generator:
      WRITE_NUMBERS_AS_STRINGS: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      retries: 5
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
    consumer:
      # Default consumer group ID
      group-id: create_voucher_order
      # Whether to auto-commit offsets
      enable-auto-commit: false
      # Automatically reset the offset when Kafka has no initial offset or the offset is out of range
      # earliest: reset to the smallest offset in the partition;
      # latest: reset to the newest offset in the partition (consume newly produced data);
      # none: throw an exception as long as any partition has no committed offset;
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual_immediate
mybatis-plus:
  type-aliases-package: org.yupeng.entity # Type alias scan package
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    local-cache-scope: statement
logging:
  level:
    org.yupeng: info
    AUDIT: INFO
  pattern:
    dateformat: mm:ss.SSS
bloom-filter:
  filters:
    shop:
      name: shop-id-bloom
      expected-insertions: 50000
      false-probability: 0.01
    voucher:
      name: voucher-id-bloom
      expected-insertions: 100000
      false-probability: 0.01
management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
  prometheus:
    metrics:
      export:
        enabled: true
      
